apiVersion: v1
kind: LimitRange
metadata:
  name: online-boutique-packaged-limits
  namespace: online-boutique-packaged
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 32Mi
      max:
        cpu: "1"
        memory: 1Gi
