---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBA/JuMmvCPRY/JGLKTwE3DaPn2Fm9UzDT6yKM2vDFtGGOfiPh4CNm7yvcQry3d6Qaj/K3iojJvUEklUpeDel5BrZaky355TRZUkURAUo/NM3dwB+c5xYcAPPNvYluh83A1GeDsaciGvGxyTjpOofaJX9xj9QMkuva2TV0m3kBYbkxnOo60J0x57dmaprUfyp5+0fswpn56rMb9+yarnUaYOYEMCYmTfOPCQYDfXixbP2LJQULxRT3JSkjLFcIT1P+vK7WzWdXI+Ps7BnZxJtcj2ykibYDmJ7k5SbTRjVdTvEJWHC2ktvduBfqdEYYUkwNc4MvNi7qYwavrv6dXzlorkP3fnLPErIj7eFGr6QakA9+35av7zUst2+H38T6HTMXSFCSoOVB/6ss+pPMq+Abo4mvny1YUHdoqsZMh6R0czMCwtBA7AwxjbDrT7pFtlWMpZtxKWU4XYR7182O/CTInKH+GkwfyPjlYOFkk2W02khvTdvo8oFyCiNIlRd7q5sOwwzzNEVRp0bTbwzM/L7kgmZrvZgHYGRG2NSKtq2ApvKGaw2TEFBmEf5eR6RCtHZ+U1jKRlOTn5Ki4w2bzHvmboDJU3c1FuRvFegPi4nlxWu7rTcintpxFoB0sxV9JeTjLkRzRqmT9vrrEDMP4ekiCpDaGZcZLSEeYj226IEjv2FYJ1HjnPZXDJl5Umb/HQRuolwRs9875DLDP8BO2v9p3+afv4zhsl+f8in1H2h3qRQ==
    admin-user: AgDKPOT0dfk8t3sd3iSg8JPScCFv7Iy2ybFY109KUjbMyyeUhJg42l8XHBZKMf06PQA6yZNALOYtUbat2hoEHs3rc3QdfdwaWv9SqKvahX/03iaBuDAHtLYvUuAQlFomaOIP8OlHiV8Hz6HrMCbIxN1omf9hnDdOA5P3Yw+tUvK7vOndwl50bUWN7fygN211ObTArrD+wotZvJH6eMeRcsGOgXfkff7DovvXTTUkgamiJbss1XTtYRGHrzoQsHEC5PYoqgV3isKmXRPZZu+AvnMKSA7Zu0cdtaeAHQYY3bbgji0FRO3Q7Z1wOFNO4tUFmcf3c2x7Qs8gHvuj+hTOQopQik7g0SQLwkJchSmdhbMvEyMPduUA3nCSvZEqjqlDP/LaSx8uAOTCf7UpMeovSnGAFXnxOLL7l5spn+rsksEaZZOR/sjxyzfyzvlbl6RLwOIJpH2SREw8n0tLOg/L1u/mlpa8TYwf5To2OYmGLd5EA7Fmk6og7YPm7rTSavFycchmgA/BI4ZfHXuEUj6CnNS+XrVthnuiFO+wIkRVLp4d0MgKoPh6urrOjXL40zkEShJSQ/S61mm/AjOMPTX9p9/b9ou9pDB52zOi6lK68bLAIrQX+kG9Vf1EJYJjduJaJzv4Qq9xiuDLG4dHyqKkL3CkQz6E/XRAJ/tNaCPg1TK1lwDLrAe/bykOwrnzv1si5iFJTeAcSw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
