---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-cart-credentials
  namespace: online-boutique-packaged
spec:
  encryptedData:
    password: AgBik7JC4u4NuvflkSO1tqxxhx8a/zD6UJ9fwhaqTCBlrWxdHvTGbmJQIzFcZZJCFIWYeCSkjdzPQWLcikUkn20d1wJ582ifQ3K1n8v+/IYMh958FvqMZIpl4wwDUYswIUm/zQD+01KYOD7/QR0iATuwDmdoScUpMfOl1uE1IN8VnEMPuje5Hszt/6xfJmT97socMMXaCa37pyNPftfYRSmJMkqkpoqOKx3aamBWUsolrReew1kvpFbSINVQ4Ldb1RZbU6wptKSd3mlxUCu9Yrb2qoKxSsTYRXwCMXUkGyUiAyQauKjysSgXOxp51LEbAbjaTRlzYfzFLlCALGsEagawkjNdHIRouDbriioaNk6WGmYI4nkbyDD0Iof6q4VWGSLecu1eFNzLlD2TsPMuDa7w4uALfugpVA/E9eEcdhqp+/27ldmNEpLbjiKSTRG61L85dhsUEiEJtjraqq5G+EDEdWnUla9uCENxO5QNQEkGrOcdk2LZ4ivFjeZCZ+rAap1BPMChuT8azH1EMpADNEx0H0v2UbaNOY4Tw8fmL+0GiYGKhCZk501bdlZhSuxzrxIDZCu092Uhlak/dnVxcwWdiCnoWUdnMNmrdwffpZOHbDZ7KS36YPOS5KeD58f1MgBhC3xOpF95kSgl7TdVE1/kBw2ONY4pTOmzWaanF5gk16bN9MmC9UVXf7OubOaZ8ShsYtq6yy1IL/stnHh8Sa8GXjNg5dKlL22P7UUgqJGm8Q==
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: online-boutique
        meta.helm.sh/release-namespace: online-boutique-packaged
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: online-boutique
        helm.sh/chart: online-boutique-0.1.0
      name: redis-cart-credentials
      namespace: online-boutique-packaged
    type: Opaque
