---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-cart-credentials
  namespace: online-boutique-packaged
spec:
  encryptedData:
    password: AgCnB0do6nmBpphFhxW6VV5E20YVuJnTQU2nqxLJigNot6fHd5wcFyDlxsBj7fYd3Co009S79zqHn8/2Ch89NFQUwCWPapmrCX/4IEzD7ZYv6HakL0AxPGb59hfCJRlDE9fNlCrfaE1HHbEbwD+n1k0FnBaqBdUK8BHbug64+vGS8FxaeKClI3pNC2parz9N0FcIQE86y3HKzqjSXETwM48oOZTpVmvdsrR5MD65dt74TLJfOn5KtNCFWamHRhKjslcXKgXrMS56U2eP2cFUHmTU0DYsdrJHIu7wC/uH0nDqlp/qp+D7gEBwsJYYCbX+06/lpou0n4C0er3XY6xRmqm85aiopV7P7ie+BqdRF10yghpMW+0P5Yoq/fV8mT0sCmQWGenmCAnGV54SWkP4bV3SqR/8y5D7PxhnrY2iUQsP/E8jLQCsxGfOi40vPVosAuWFjcQrzfrzAyCA5Htlmc2WJ8A9sGAMWX+Kc5365bSZU0UAsYT0MFc3E1hABLs7HjzV2/pBCczp6qbTEqKl25Q7YwhMIp5rCjJhbE3N34sq8Xn83CqGjFYKJZ4MCCrLHAG8EjRjhUWdu8mKlnqIBWNCU2xVgc6nz1n0sDJsGby32SJI4E9zzd86rjEfDAgh+tOU+Hxl4dtZly/K86wSgtum2wmxkYOOOIHYlQFwC1S9tPX7RnIy7AHfhV9kx1LRMB304IFC1X6oWwwmnIxEAqTEfDKlXI8E2k8taVY0tUmvIQ==
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: online-boutique
        meta.helm.sh/release-namespace: online-boutique-packaged
        sealedsecrets.bitnami.com/managed: "true"
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: online-boutique
        helm.sh/chart: online-boutique-0.1.0
      name: redis-cart-credentials
      namespace: online-boutique-packaged
    type: Opaque
