apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-packaged
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/ics-msrj/ics-ms-kubernetes-labs.git
      targetRevision: main
      path: charts/online-boutique
      helm:
        releaseName: online-boutique
        parameters:
          - name: redisCart.storageClassName
            value: alicloud-disk-essd
          - name: redisCart.storageSize
            value: 20Gi
          - name: nodeSelector.workload
            value: autoscale
          - name: redisCart.createSecret
            value: "false"
    - repoURL: https://github.com/ics-msrj/ics-ms-kubernetes-labs.git
      targetRevision: main
      path: gitops/sealed-secrets/ack/online-boutique-packaged
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique-packaged
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
