apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/ics-msrj/ics-ms-kubernetes-labs.git
      targetRevision: main
      path: kustomize/overlays/dev
      kustomize:
        patches:
          - target:
              kind: Secret
              name: redis-cart-credentials
            patch: |-
              apiVersion: v1
              kind: Secret
              metadata:
                name: redis-cart-credentials
              $patch: delete
          - target:
              kind: Deployment
            patch: |-
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  workload: autoscale
          - target:
              kind: StatefulSet
            patch: |-
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  workload: autoscale
              - op: replace
                path: /spec/volumeClaimTemplates/0/spec/storageClassName
                value: alicloud-disk-essd
              - op: replace
                path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
                value: 20Gi
    - repoURL: https://github.com/ics-msrj/ics-ms-kubernetes-labs.git
      targetRevision: main
      path: gitops/sealed-secrets/ack/online-boutique-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
