---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-cart-credentials
  namespace: online-boutique-dev
spec:
  encryptedData:
    password: AgAjhi/oDT54btkdxQcp3jImQS+Jo3U8dx2K0DFN4TNNqp2fUyRHnamRIhbirCQk6/J7TVsZZci8iI9wJC3GT9ir7eVN5VSareO7r5SY7df8ZERKyOCWeLB3VCuJCoAz0deGWTCz0WbwAfzLNEd4VZ2bGnyEFmjyQwS4SEEEoRNv9qfs7mgcyzmWYLcwLxMALa/wcc7L+gM/UmlPmsWMMdR0eeuGsLRDL9GaNaNIhHXEN0AZLdM+9a2/+Y5fHWZc49bk7AvKw2VEFuhxnh6XwA+i6efUtELIDr7/2/dgzWZ9siPl/F5G7Xt1XxJ13miQt/zCRcC+1spu83UcEANP547Ay2a2VauBb4NzspPHEnWvVMjC3vgckkZwGV7tOG/LeWWm2AkhMRUi+iic1mI1uiwXv4gyiJ/e8Dnls1jHxUcopkQTUCcrnlejdQCkOgx8wYHhkjSzM2Pk2ZT7d3Uqxnlw+zK0x+WDNLos3N9iQAA2VoFizUoTJV9wL5YO1OA54ipz9LH3ihQ0VhZ3jPD8hl/B7A3QAvT7bNOAFU7ecnwJU+JCeRtBZHifZhrBEfl9VxCymgntfONQxOzi9IhdR02IdLNjbr5nEGFcLzlAnU9z5zbePPr26C7khiz+ARf3XI9mrWddHYWjSvby6ANGl64Bwy6Qus8I2i7xGPmA0Ejr68p/l/0MfFW1skIQxmSKK2SWJelBT03s9bbwC43+0v0/mjHmiPMVPehNxMGefMiypQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: redis-cart-credentials
      namespace: online-boutique-dev
    type: Opaque
