---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-cart-credentials
  namespace: online-boutique-dev
spec:
  encryptedData:
    password: AgCQNjiPrK/GzGacs2OHzzw1yUAwok1qTl57IdApwwtP1X6j071Hd2ycwI22N0+1h6imS26r6kf2aVDOLQkTDcTko+y6UVrPhmWmvpArl05s7WejmBlxa4BOcX7QTq2zkI/rZyXseNpc/FYfJreCzlBK8dLw9nf/zHNUk9jVKWYU5rX4UI2AVGOs0pnWhdNyuEJTHykGLu8GLWen/2AXGsmEJ5GGopOK1mEwlv2DLy7s9cBzLPenjvDr3yrNfq4fRb6yuI4CeAcw8s3o3zyaKBw2Y6ytU0WKCFPl8LgkMcQaWvJkNiRuw09hDaKyTUtKwgmZaigkKO2CHo1GkfA+vB6By66mqLA+6k3Kr8lnxQ/wyxeMPFx2Mhdb2VJTULYs9yJFkbXeprRzvYsQogskcBaN896ouqW6VnhaQLmkoWORSSZZEL7yLNoQ8lq04u6Cjb9DSB76Ag499RJRvobuoJvoJAQ65rH2gSS0PTGBEXpGskyFGiCVZw6G3cPpUjgTrd5JrybDVbEba8ba+uc//B8SBMH4yTLh0dmvKx3oYUov0lmo3H50qCefS0sx0R7P9dDl591/kCJ/M+FWQHVhSBtXWxPDZ9b4n9CQ7dB6CbyF0MKV6F234E78Z27JYMO18nrlj9z8FIVBL3+H2vJZOLN7zth8J8+hbqByQFWDteV1+autcV21iBy586Zv00qmo6rz4E/WppakCMXEap3YuHIFbWB0M3U6kmsnO/7r5g9PeQ==
  template:
    metadata:
      name: redis-cart-credentials
      namespace: online-boutique-dev
    type: Opaque
