---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgByUXIIG942mn+nQCDYDoGjJ/yOJXqk/ftickZRxXHhtWdDkjqKq6L7BK75c7iiipNfbn5+YbDoh+2p+CV08FXF6XcZdePx98D+k/tHAWuIRhKP7sZOxWlFOutHLN/MPu/OT8nELYn0yKWQNuNCg4nYkzuB7u0f1PAyUkvNKBC7FjjnKd/aNr10l4K0r8c1A/JG3maao2LVJcP+CQ0jTdtm+JEkyNX3DjU87HVlI7T850Lz8lv/XZzOZ64yx/Twyk2j6S43odd1kmKk4cMAtenG9gXLqnGM5IMk5g23sYbHMJC17O3s1WyuH63/xnGnB3b0yrcXxNw5AIdCkgbdqJXy5R2J03BRkx3InTcYzSmS5DJv5+8QxWlXh3qlhh15A7ffSx41lD0MsL+DDQm+9fzhNUM2jeH8oPozMlfTvLO7upo9wOe9uge643VSR4CjQFMf1wE4whCSbcXfqdNKdUFZ0wtU8mY67eEK4XyskevmoEWnhLBfHtIsZgY6qXxUZaEzQeC+UgiLq4OkgN2FEY4PJRQf5kf8r/oA+OBMt7BFsiLDCtqXK992Poz6DUI1m9sbvzipb0mGrZOv8EyEpbn0OuS3sLtMKBSHH72MIQKNo2sFCGP4E4RM+1yZqelTNOiaGYRih4IaKmnhDa2o1gHp8fQKvks1dNR/YWRpJZZbbNnk3w47y9EDtB5tXOxW073BsCPcHi0bZ2eJdrUL1yMI20VNf/BU3M6SlQNlwbsnJQ==
    admin-user: AgCimYJ0M8pPY+4xhW8+VuOR7w9U9VZauMbm6uy9G9EnhK6O9VXF63Zq6Mb/eyrb+2cWeVipprmf+nawjv97QUOBByeS/PZp15BgwWYKZmOhGt4uAumqfZXCMgCLdRpFmKv+lLNDgtC8g+CFcbrvrEKLGa80pY3EWxlpo9iAgrsIjHGT+HuYmIM6CCAVpseJzbevAVK37Fzy4WthwiEbqMWgrNZ1VW0ggBihtG2T54YKLaKJPgmJi2RoG2L+RU7Bl/PH+Unhgt0HEySHGCalj3a1vx116HmR+9QvGCd9Y1JcIeqXyGv3Jv+tAP52QyTTlrSt0d53v7gyKIz84Html/xdhW7rKCMDN13e31zdIai2TtILwD5gcRo58/HSYiFavutgrhE1H9Jj8DqLM7WD4GclyMIld8WGucrnkQTnR0ptI/EalgrF6ny1be8RQ+mxPkb3a2/ZjUeAfZy7p+Aid09VBtO6dczhggdMsJ5CRDf2k9JSWNz2qUTPVSPv6DfHWyPJRo6zjJO0XDg5Hcj8RCu9Vrymqrb0WJdq6xG4t3yZ8dYfXUvv1GSVURrglgEj6VOuH/i39DT9FIck8EFBu1CLz/4Z/UHiz/ZRo175byRWHUEBqUEv4L8k/BlaCR2nVRBrJuZnU4xArlqzgs2oav+3fNrbmPC/6YSkdENoxAZNRXiCD5+1nAHYSwMyB4CBMY9KDVYXqA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
