# Same as online-boutique-packaged's copy — see that file's comment.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-cart-credentials
  namespace: online-boutique-dev
spec:
  encryptedData:
    password: AgASYBJUm1Pu4cRAYzwcWPNjqNTkLdWiQ3KRVgUiSgGw9NzOm5+a829nbYGLzZmjHCZAcP3C5nMnchaa0X2+979iiAq8ESdt0u5k8Ba00aUGz7lv/hN4gSn0clQZia9HnSAIF9Tu5wCr7EbvlTFZUwupOyemCUXzuLAqYs5Tv+bQRhMurXXsFYunuBlP2nIk8cNRCy+AzjXqcQDBPqk6233JqIibSYE4ik7z0SyWvR1ZdaG1ApVLOnCJ5jptxF3fgJzZ1SfA0u6k0NtfYbpHNZ/kaqR6CLsOZszibEiPN4ytE91N1ksX1VVZhstHhAUsR3wlLRBtNWN8TAh0HoQH5OhcaZp0Lr6jyUHuuRpguVlcaKotMRPqOrm47lTiTXqCfDzl1TSZgvT2kHvYNmrYPj4TwVEjhdSb5UFiuHcUFfjWpGh3MlNAU7NUmjmE15WOnsiwUZO95dXNy8ynzH6C1fVitXRa58ahwNH/4vY+hYDG2Hfl28G87nFgVkwNwyCUgD95NfMmIYCK4UgRytPQbReUvvbLhHNoiCdAbpGldffJUwpxwqA/xk5o29qyuROsqdExO2fStk8F5Fbtt0Zkhpekqh40LAD9N1zAW5ykX6DdECSBVBVmHDmFniUsWDv0CK1gsmgoywcvfqanyLp+MIexd94VmRfPIRGwqjU83WzPTLf6v7JBtBKibd3aIGN2wXVNnGEC4txx549LVolGDoQPbrMclkX+PqyHZvCvlyLbPQ==
  template:
    metadata:
      name: redis-cart-credentials
      namespace: online-boutique-dev
